; PlatformIO configuration file for ESP32-S3
; Basic configuration for general-purpose projects

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Common library dependencies
lib_deps =
    ESP Async WebServer
    WebSockets
    me-no-dev/AsyncTCP
    madhephaestus/ESP32Servo @ ^0.13.0
    bblanchon/ArduinoJson @ ^6.21.5
    gin66/FastAccelStepper
    thomasfredericks/Bounce2

; Ignore specific libraries if they cause conflicts
lib_ignore = AsyncTCP_RP2040W

; Build settings
build_type = release
build_flags =
    -DCORE_DEBUG_LEVEL=3  ; Moderate debug level
    -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/WiFi/src
    -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/FS/src
    -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/SPIFFS/src

; Serial upload settings - for USB upload
; upload_speed = 921600
; upload_protocol = esptool
; upload_port = /dev/cu.usbmodem1101

; Monitor settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; ESP32-S3 specific options
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.partitions = default.csv

; OTA settings
upload_protocol = espota
upload_port = 192.168.1.252 ; Set the desired upload IP
; upload_flags =
;     --auth=your_ota_password
